
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-staff-service
  namespace: default
spec:
  hosts:      # which incoming host are we applying the proxy rules to???
    - "fleetman-staff-service" # Copy the value in the gateway hosts - usually a Domain Name
  http:
  - match:
    - headers:   # IF
        my-header:
          exact: canary
    route:     #THEN
    - destination:
        host: fleetman-staff-service
        subset: risky
  - route:    # CACHE ALL
    - destination:
        host: fleetman-staff-service
        subset: safe
 
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-staff-service
  namespace: default
spec:
  host: fleetman-staff-service
  subsets:
    - labels:
        version: safe
      name: safe
    - labels:
        version: risky
      name: risky
