---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-staff-service  # just a name of virtual service , you can give any name
  namespace: default
spec:
  hosts:
    - fleetman-staff-service.default.svc.cluster.local   # k8s service dns name , 
  http:
    - route:
        - destination:
            host: fleetman-staff-service.default.svc.cluster.local           # target dns name
            subset: risky
          weight: 10
        - destination:
            host: fleetman-staff-service.default.svc.cluster.local              # target dns name
            subset: safe
          weight: 90
---
kind: DestinationRule           #defining which pod should be part of each subset
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-staff-service
  namespace: default
spec:
  host: fleetman-staff-service.default.svc.cluster.local
  subsets:
    - labels:
        version: risky
      name: risky
    - labels:
        version: safe
      name: safe
